"""Provisioning logic for runtime deployment artifacts.

These artifacts (currently the codex ``CODEX_HOME`` config) are *generated*
from the repo location + the worker's deployment root, never tracked with one
machine's absolute paths baked in. The repo-internal paths come from
``paths``; the deployment root is operator data passed in. This is the seed of
the Slice 4 ``onboard`` command — for now it materializes the pilot codex
worker's home.
"""

from __future__ import annotations

import os
import sys
import uuid
from pathlib import Path

from . import paths
from .policies import WORKER_DISPATCH_POLICY_VERSION
from .schema import ValidationError, identity_to_path_segment


def _resolved_within(child: Path, root: Path) -> bool:
    """True when ``child`` resolves inside ``root`` (both fully resolved)."""
    try:
        child_resolved = child.resolve()
        root_resolved = root.resolve()
    except OSError:
        return False
    if child_resolved == root_resolved:
        return True
    return root_resolved in child_resolved.parents


def refuse_home_outside_custody_root(codex_home: Path) -> None:
    """Refuse a production Codex home resolved outside the runtime custody root.

    Containment is production-authoritative: it is ALWAYS enforced against the
    runtime custody root (``paths.codex_custody_root()``), never gated on an
    environment switch that production never sets. Scratch/test materialization
    opts out explicitly via ``write_codex_home(..., enforce_custody_root=False)``.
    """
    root = paths.codex_custody_root()
    if not _resolved_within(codex_home, root):
        raise ValidationError(
            "refusing to provision a Codex home outside the runtime custody root; "
            f"home={codex_home}; custody_root={root}; "
            "provision it under the custody root (the default home), or "
            "pass enforce_custody_root=False for scratch/test materialization"
        )


def render_codex_base_config(actor_id: str, project_root: str) -> str:
    """The base ``config.toml`` codex loads from a redirected ``CODEX_HOME``.

    ``mcp_servers`` MUST live in base (not the profile) per codex's loading
    rule. The MCP launcher path is derived from the repo, so the repo can move
    without editing this file; the operator's home and the worker's
    ``project_root`` are trusted sandbox roots.
    """
    return "\n".join(
        [
            "# Generated by agent_comms.provisioning (do not hand-edit; regenerate).",
            "# mcp_servers MUST live in base (not profile) per codex's loading rule.",
            "",
            "[mcp_servers.agent-comms]",
            f'command = "{paths.mcp_command()}"',
            f'args = ["--actor-id", "{actor_id}"]',
            "# Auto-approve MCP tool calls in headless `codex exec` mode; without",
            "# this, calls silently cancel (MCP tool approval gate).",
            'default_tools_approval_mode = "approve"',
            "",
            "[mcp_servers.agent-comms.env]",
            'WAKE_POLICY = "worker_dispatch_readwrite_bounded"',
            f'WAKE_POLICY_VERSION = "{WORKER_DISPATCH_POLICY_VERSION}"',
            f'AGENT_COMMS_ACTOR_ID = "{actor_id}"',
            f'AGENT_COMMS_PROJECT_ROOT = "{project_root}"',
            "",
            f'[projects."{project_root}"]',
            'trust_level = "trusted"',
            "",
            f'[projects."{Path.home()}"]',
            'trust_level = "trusted"',
            "",
        ]
    )


def render_codex_profile_config(project_root: str) -> str:
    """The per-actor ``<actor_id>.config.toml`` layered via ``--profile``.

    Profile-only fields; ``mcp_servers`` would NOT load from here.
    """
    return "\n".join(
        [
            "# Generated by agent_comms.provisioning (do not hand-edit; regenerate).",
            "# Layered via --profile on top of base; profile-only fields.",
            "",
            'sandbox_mode = "workspace-write"',
            'approval_policy = "never"',
            "",
            f'[projects."{project_root}"]',
            'trust_level = "trusted"',
            "",
        ]
    )


def write_codex_home(
    codex_home: Path,
    actor_id: str,
    project_root: str,
    *,
    auth_source: Path | None = None,
    enforce_custody_root: bool = False,
) -> list[Path]:
    """Materialize the codex base + profile config into ``codex_home``.

    Returns the written paths. Auth is optionally linked from a shared source;
    this always (re)writes the two generated config files. This stays a reusable
    low-level primitive: ``enforce_custody_root`` defaults to ``False`` so
    existing scratch callers keep working without edits. Production onboarding /
    provision commands pass ``enforce_custody_root=True`` explicitly so a home
    resolved outside the runtime custody root refuses before any mutation.
    """
    if enforce_custody_root:
        refuse_home_outside_custody_root(codex_home)
    actor_segment = identity_to_path_segment(actor_id)
    codex_home.mkdir(parents=True, exist_ok=True)
    base = codex_home / "config.toml"
    profile = codex_home / f"{actor_segment}.config.toml"
    base.write_text(render_codex_base_config(actor_id, project_root))
    profile.write_text(render_codex_profile_config(project_root))
    written = [base, profile]

    if auth_source is None:
        return written

    auth_source = auth_source.resolve()
    if not auth_source.is_file():
        print(
            f"warning: auth source {auth_source} not a regular file; "
            f"you must authenticate codex in {codex_home} before dispatching",
            file=sys.stderr,
        )
        return written

    target = codex_home / "auth.json"
    if target.is_symlink():
        pass
    elif target.is_file():
        print(
            f"warning: regular file at {target} not replaced; remove "
            f"by hand to enable shared-auth symlink",
            file=sys.stderr,
        )
        return written
    elif target.exists():
        raise RuntimeError(
            f"unexpected non-file non-symlink at {target}; refusing to install symlink"
        )

    tmp = target.with_name(f".auth.json.{os.getpid()}.{uuid.uuid4().hex}.new")
    try:
        tmp.symlink_to(auth_source)
        os.replace(tmp, target)
    finally:
        tmp.unlink(missing_ok=True)
    written.append(target)
    return written
