from __future__ import annotations

from . import (
    init,
    bootstrap,
    provision_codex_home,
    refresh_codex_auth,
    codex_auth_targets,
    onboard_worker,
    register,
    rerender_spawn,
    agents,
    actors,
    admin,
    dispatch_start,
    dispatch_status,
    handoff,
    inbox,
    unread,
    read,
    ack,
    close,
    wait,
    payload_audit,
    post_status,
    status,
    version,
)

COMMAND_MODULES = [
    init,
    bootstrap,
    provision_codex_home,
    refresh_codex_auth,
    codex_auth_targets,
    onboard_worker,
    register,
    rerender_spawn,
    agents,
    actors,
    admin,
    dispatch_start,
    dispatch_status,
    handoff,
    inbox,
    unread,
    read,
    ack,
    close,
    wait,
    payload_audit,
    post_status,
    status,
    version,
]

COMMANDS = {module.NAME: module for module in COMMAND_MODULES}
